import type { App } from "obsidian";
import type { CalloutDefinition } from "../types";
import { hexToRgbString } from "../utils/colorUtils";
import { materialFontFamily, svgToDataUri } from "../utils/iconLoader";
import type { CalloutRegistry } from "./CalloutRegistry";

const STYLE_ELEMENT_ID = "callout-studio-styles";
const MATERIAL_FONT_LINK_ID = "callout-studio-material-font";
const DEBOUNCE_MS = 300;

export class CSSInjector {
	private styleEl: HTMLStyleElement | null = null;
	private debounceTimer: number | null = null;
	private registry: CalloutRegistry;
	private app: App;

	constructor(app: App, registry: CalloutRegistry) {
		this.app = app;
		this.registry = registry;
	}

	initialize(): void {
		this.ensureStyleElement();
		this.inject();
	}

	private ensureStyleElement(): void {
		if (this.styleEl) return;
		const existing = document.getElementById(
			STYLE_ELEMENT_ID,
		) as HTMLStyleElement | null;
		if (existing) {
			this.styleEl = existing;
			return;
		}
		// eslint-disable-next-line obsidianmd/no-forbidden-elements -- dynamic CSS injection requires a style element
		this.styleEl = document.createElement("style");
		this.styleEl.id = STYLE_ELEMENT_ID;
		document.head.appendChild(this.styleEl);
	}

	inject(): void {
		this.ensureStyleElement();
		if (!this.styleEl) return;

		const callouts = this.registry.getAll();
		const rules: string[] = [
			"/* Auto-generated by Callout Studio — do not edit manually */",
		];

		const materialFonts = new Set<string>();

		for (const def of callouts) {
			if (def.icon.type === "material") {
				materialFonts.add(def.icon.style ?? "outlined");
			}
			rules.push(this.generateCalloutCSS(def));
		}

		// Handle Material Icons fonts
		this.updateMaterialFontLinks(materialFonts);

		// If we have material icons, add the required CSS for font rendering
		if (materialFonts.size > 0) {
			rules.push(this.getMaterialIconBaseCSS());
		}

		this.styleEl.textContent = rules.join("\n\n");
	}

	private generateCalloutCSS(def: CalloutDefinition): string {
		const lightRgb = hexToRgbString(def.colorLight);
		const darkRgb = hexToRgbString(def.colorDark);
		const iconCSS = this.getIconCSS(def);

		const parts: string[] = [];

		// Light mode (default)
		parts.push(
			`.callout[data-callout="${def.id}"] {\n` +
				`  --callout-color: ${lightRgb};\n` +
				(iconCSS ? `  --callout-icon: ${iconCSS};\n` : "") +
				`}`,
		);

		// Dark mode override (only if different from light)
		if (def.colorLight !== def.colorDark) {
			parts.push(
				`.theme-dark .callout[data-callout="${def.id}"] {\n` +
					`  --callout-color: ${darkRgb};\n` +
					`}`,
			);
		}

		// Material icon font override
		if (def.icon.type === "material") {
			parts.push(this.generateMaterialIconOverride(def));
		}

		// Icon position/size transform
		const iconTransform = this.getIconTransformCSS(def);
		if (iconTransform) {
			parts.push(iconTransform);
		}

		return parts.join("\n\n");
	}

	private getIconTransformCSS(def: CalloutDefinition): string {
		const ox = def.iconOffsetX ?? 0;
		const oy = def.iconOffsetY ?? 0;
		const scale = def.iconSize ?? 1;
		if (ox === 0 && oy === 0 && scale === 1) return "";

		const transforms: string[] = [];
		if (ox !== 0 || oy !== 0) transforms.push(`translate(${ox}px, ${oy}px)`);
		if (scale !== 1) transforms.push(`scale(${scale})`);

		return (
			`.callout[data-callout="${def.id}"] > .callout-title > .callout-icon {\n` +
			`  transform: ${transforms.join(" ")};\n` +
			`  transform-origin: center;\n` +
			`}`
		);
	}

	private getIconCSS(def: CalloutDefinition): string {
		switch (def.icon.type) {
			case "lucide":
				// getIconIds() already returns IDs with the "lucide-" prefix
				return def.icon.value;
			case "svg": {
				// Look up SVG content from registry
				const svgData = this.registry.customSvgIcons.find(
					(s) => s.name === def.icon.value,
				);
				if (svgData) {
					return svgToDataUri(svgData.svg);
				}
				return `lucide-pencil`;
			}
			case "material":
				// Material icons use font ligatures, not SVG.
				// We set a special CSS custom property and override rendering.
				return `lucide-pencil`; // fallback for --callout-icon
			case "emoji":
				return `"${def.icon.value}"`;
			default:
				return "";
		}
	}

	private generateMaterialIconOverride(def: CalloutDefinition): string {
		if (def.icon.type !== "material") return "";
		const fontFamily = materialFontFamily(def.icon.style ?? "outlined");
		const isFilled = def.icon.style === "filled";
		return (
			`.callout[data-callout="${def.id}"] > .callout-title > .callout-icon::after {\n` +
			`  content: "${def.icon.value}";\n` +
			`  font-family: "${fontFamily}";\n` +
			`  font-size: 24px;\n` +
			`  line-height: 1;\n` +
			`  letter-spacing: normal;\n` +
			`  text-transform: none;\n` +
			`  white-space: nowrap;\n` +
			`  direction: ltr;\n` +
			`  -webkit-font-feature-settings: "liga";\n` +
			`  font-feature-settings: "liga";\n` +
			`  -webkit-font-smoothing: antialiased;\n` +
			(isFilled ? `  font-variation-settings: 'FILL' 1;\n` : "") +
			`}\n` +
			`.callout[data-callout="${def.id}"] > .callout-title > .callout-icon > svg {\n` +
			`  display: none;\n` +
			`}`
		);
	}

	private updateMaterialFontLinks(needed: Set<string>): void {
		// Map styles to Google Fonts family names
		const FONT_FAMILIES: Record<string, string> = {
			outlined: "Material+Symbols+Outlined",
			rounded: "Material+Symbols+Rounded",
			sharp: "Material+Symbols+Sharp",
			// "filled" uses the Outlined font with FILL variation setting
			filled: "Material+Symbols+Outlined",
		};

		// Determine which font families are actually needed
		const neededFamilies = new Set<string>();
		for (const style of needed) {
			const family = FONT_FAMILIES[style];
			if (family) neededFamilies.add(family);
		}

		// Remove font links that are no longer needed
		const existingLinks = Array.from(
			document.querySelectorAll<HTMLLinkElement>(
				`link[id^="${MATERIAL_FONT_LINK_ID}"]`,
			),
		);
		for (const link of existingLinks) {
			const family = link.getAttribute("data-family");
			if (!family || !neededFamilies.has(family)) {
				link.remove();
			} else {
				neededFamilies.delete(family); // already loaded
			}
		}

		// Add missing font links
		for (const family of neededFamilies) {
			// eslint-disable-next-line obsidianmd/no-forbidden-elements -- dynamic font loading requires a link element
			const link = document.createElement("link");
			link.id = `${MATERIAL_FONT_LINK_ID}-${family}`;
			link.setAttribute("data-family", family);
			link.rel = "stylesheet";
			link.href = `https://fonts.googleapis.com/css2?family=${family}:opsz,wght,FILL,GRAD@24,400,0..1,0`;
			document.head.appendChild(link);
		}
	}

	private getMaterialIconBaseCSS(): string {
		return (
			`/* Material Symbols base */\n` +
			`.material-symbols-outlined {\n` +
			`  font-family: "Material Symbols Outlined";\n` +
			`  font-weight: normal;\n` +
			`  font-style: normal;\n` +
			`  font-size: 24px;\n` +
			`  line-height: 1;\n` +
			`  letter-spacing: normal;\n` +
			`  text-transform: none;\n` +
			`  white-space: nowrap;\n` +
			`  word-wrap: normal;\n` +
			`  direction: ltr;\n` +
			`  -webkit-font-feature-settings: "liga";\n` +
			`  font-feature-settings: "liga";\n` +
			`  -webkit-font-smoothing: antialiased;\n` +
			`}`
		);
	}

	scheduleInject(): void {
		if (this.debounceTimer !== null) {
			window.clearTimeout(this.debounceTimer);
		}
		this.debounceTimer = window.setTimeout(() => {
			this.inject();
			this.debounceTimer = null;
		}, DEBOUNCE_MS);
	}

	destroy(): void {
		if (this.debounceTimer !== null) {
			window.clearTimeout(this.debounceTimer);
			this.debounceTimer = null;
		}
		if (this.styleEl) {
			this.styleEl.remove();
			this.styleEl = null;
		}
		// Remove Material font links
		document
			.querySelectorAll(`link[id^="${MATERIAL_FONT_LINK_ID}"]`)
			.forEach((el) => el.remove());
	}
}
