/**
 * manager/CSSInjector.ts — Generates and injects dynamic CSS for all callouts.
 *
 * Reads every CalloutDefinition from the registry and writes a single
 * `<style>` element into the document head with per-callout CSS custom
 * properties (colors, icon offsets, sizes). Debounces rapid successive calls
 * so the DOM is only updated once after a batch of registry changes.
 * Also manages the Material Symbols font link element when needed.
 */
import { setIcon } from "obsidian";
import type { App } from "obsidian";
import type { CalloutDefinition } from "../types";
import { hexToRgbString } from "../utils/colorUtils";
import { svgToDataUri } from "../utils/iconLoader";
import type { CalloutRegistry } from "./CalloutRegistry";

const STYLE_ELEMENT_ID = "callout-studio-styles";
const MATERIAL_FONT_LINK_ID = "callout-studio-material-font";
const DEBOUNCE_MS = 300;

export class CSSInjector {
	private styleEl: HTMLStyleElement | null = null;
	private debounceTimer: number | null = null;
	private injecting = false;
	private registry: CalloutRegistry;
	private app: App;

	constructor(app: App, registry: CalloutRegistry) {
		this.app = app;
		this.registry = registry;
	}

	initialize(): void {
		this.ensureStyleElement();
		this.inject();
	}

	private ensureStyleElement(): void {
		if (this.styleEl) return;
		const existing = document.getElementById(
			STYLE_ELEMENT_ID,
		) as HTMLStyleElement | null;
		if (existing) {
			this.styleEl = existing;
			return;
		}
		// eslint-disable-next-line obsidianmd/no-forbidden-elements -- dynamic CSS injection requires a style element
		this.styleEl = document.createElement("style");
		this.styleEl.id = STYLE_ELEMENT_ID;
		document.head.appendChild(this.styleEl);
	}

	inject(): void {
		if (this.injecting) return;
		this.injecting = true;
		this.ensureStyleElement();
		if (!this.styleEl) {
			this.injecting = false;
			return;
		}

		const callouts = this.registry.getAll();
		const rules: string[] = [
			"/* Auto-generated by Callout Studio — do not edit manually */",
		];

		// Global callout style rules
		rules.push(this.generateGlobalStyleCSS());

		const materialFonts = new Set<string>();

		for (const def of callouts) {
			rules.push(this.generateCalloutCSS(def));
		}

		// Fallback rule: style unrecognized callout IDs with the fallback callout
		rules.push(this.generateFallbackCSS(callouts));

		// Clean up any leftover material font links (no longer needed for rendering)
		this.updateMaterialFontLinks(materialFonts);

		this.styleEl.textContent = rules.join("\n\n");

		// Lucide icon SVGs are static DOM elements injected once by Obsidian during
		// rendering. Changing --callout-icon via CSS alone does not update them.
		// Re-inject icons for all currently rendered callouts so the change is
		// visible immediately without requiring the user to re-open the note.
		this.refreshCalloutIconsInDOM();

		// Trigger Obsidian to re-render callouts with updated styles
		this.app.workspace.trigger("css-change");
		this.injecting = false;
	}

	private generateCalloutCSS(def: CalloutDefinition): string {
		const lightRgb = hexToRgbString(def.colorLight);
		const darkRgb = hexToRgbString(def.colorDark);
		const iconCSS = this.getIconCSS(def);

		const parts: string[] = [];

		// Light mode (default)
		const lightProps: string[] = [`  --callout-color: ${lightRgb};`];
		if (iconCSS) lightProps.push(`  --callout-icon: ${iconCSS};`);
		if (def.bgColorLight) {
			lightProps.push(`  background-color: ${def.bgColorLight};`);
		}
		parts.push(
			`.callout[data-callout="${def.id}"] {\n${lightProps.join("\n")}\n}`,
		);

		// Dark mode override
		if (
			def.colorLight !== def.colorDark ||
			def.bgColorLight !== def.bgColorDark
		) {
			const darkProps: string[] = [`  --callout-color: ${darkRgb};`];
			if (def.bgColorDark) {
				darkProps.push(`  background-color: ${def.bgColorDark};`);
			}
			parts.push(
				`.theme-dark .callout[data-callout="${def.id}"] {\n${darkProps.join("\n")}\n}`,
			);
		}

		// Content text color overrides
		if (def.textColorLight) {
			parts.push(
				`.callout[data-callout="${def.id}"] > .callout-content {\n` +
					`  color: ${def.textColorLight};\n` +
					`}`,
			);
		}
		if (def.textColorDark && def.textColorDark !== def.textColorLight) {
			parts.push(
				`.theme-dark .callout[data-callout="${def.id}"] > .callout-content {\n` +
					`  color: ${def.textColorDark};\n` +
					`}`,
			);
		}

		// Material icon SVG override (uses mask-image with cached SVG data URI)
		if (def.icon.type === "material") {
			const cached = this.registry.findMaterialSvg(
				def.icon.value,
				def.icon.style ?? "outlined",
				def.icon.weight ?? 400,
			);
			if (cached) {
				parts.push(
					this.generateMaterialSvgOverride(def.id, cached.svg),
				);
			}
		}

		// Icon position/size transform
		const iconTransform = this.getIconTransformCSS(def);
		if (iconTransform) {
			parts.push(iconTransform);
		}

		// Generate alias selectors that reference the same styles
		if (def.aliases && def.aliases.length > 0) {
			for (const alias of def.aliases) {
				parts.push(
					`/* alias: ${alias} → ${def.id} */\n` +
						`.callout[data-callout="${alias}"] {\n${lightProps.join("\n")}\n}`,
				);
				if (
					def.colorLight !== def.colorDark ||
					def.bgColorLight !== def.bgColorDark
				) {
					const aliasDarkProps: string[] = [
						`  --callout-color: ${darkRgb};`,
					];
					if (def.bgColorDark) {
						aliasDarkProps.push(
							`  background-color: ${def.bgColorDark};`,
						);
					}
					parts.push(
						`.theme-dark .callout[data-callout="${alias}"] {\n${aliasDarkProps.join("\n")}\n}`,
					);
				}
				if (def.textColorLight) {
					parts.push(
						`.callout[data-callout="${alias}"] > .callout-content {\n  color: ${def.textColorLight};\n}`,
					);
				}
				if (
					def.textColorDark &&
					def.textColorDark !== def.textColorLight
				) {
					parts.push(
						`.theme-dark .callout[data-callout="${alias}"] > .callout-content {\n  color: ${def.textColorDark};\n}`,
					);
				}
				if (def.icon.type === "material") {
					const cachedAlias = this.registry.findMaterialSvg(
						def.icon.value,
						def.icon.style ?? "outlined",
						def.icon.weight ?? 400,
					);
					if (cachedAlias) {
						parts.push(
							this.generateMaterialSvgOverride(
								alias,
								cachedAlias.svg,
							),
						);
					}
				}
				const aliasTransform = this.getIconTransformCSS({
					...def,
					id: alias,
				});
				if (aliasTransform) {
					parts.push(aliasTransform);
				}
			}
		}

		return parts.join("\n\n");
	}

	private getIconTransformCSS(def: CalloutDefinition): string {
		const ox = def.iconOffsetX ?? 0;
		const oy = def.iconOffsetY ?? 0;
		const scale = def.iconSize ?? 1;
		if (ox === 0 && oy === 0 && scale === 1) return "";

		const transforms: string[] = [];
		if (ox !== 0 || oy !== 0)
			transforms.push(`translate(${ox}px, ${oy}px)`);
		if (scale !== 1) transforms.push(`scale(${scale})`);

		return (
			`.callout[data-callout="${def.id}"] > .callout-title > .callout-icon {\n` +
			`  transform: ${transforms.join(" ")};\n` +
			`  transform-origin: center;\n` +
			`}`
		);
	}

	private getIconCSS(def: CalloutDefinition): string {
		switch (def.icon.type) {
			case "lucide":
				// getIconIds() already returns IDs with the "lucide-" prefix
				return def.icon.value;
			case "material": {
				// Always use pencil fallback for --callout-icon.
				// The actual icon is rendered via ::after mask-image when SVG is cached.
				return `lucide-pencil`;
			}
			case "emoji":
				return `"${def.icon.value}"`;
			default:
				return "";
		}
	}

	/**
	 * Generates CSS that renders a Material icon from a cached SVG data URI
	 * using mask-image. Works in PDF export (no external font needed).
	 */
	private generateMaterialSvgOverride(
		calloutId: string,
		svg: string,
	): string {
		const dataUri = svgToDataUri(svg);
		return (
			`.callout[data-callout="${calloutId}"] > .callout-title > .callout-icon > svg {\n` +
			`  display: none;\n` +
			`}\n` +
			`.callout[data-callout="${calloutId}"] > .callout-title > .callout-icon::after {\n` +
			`  content: "";\n` +
			`  display: inline-block;\n` +
			`  width: var(--icon-size, 1.2em);\n` +
			`  height: var(--icon-size, 1.2em);\n` +
			`  -webkit-mask-image: ${dataUri};\n` +
			`  mask-image: ${dataUri};\n` +
			`  -webkit-mask-size: contain;\n` +
			`  mask-size: contain;\n` +
			`  -webkit-mask-repeat: no-repeat;\n` +
			`  mask-repeat: no-repeat;\n` +
			`  background-color: rgb(var(--callout-color));\n` +
			`}`
		);
	}

	private updateMaterialFontLinks(needed: Set<string>): void {
		// Map styles to Google Fonts family names
		const FONT_FAMILIES: Record<string, string> = {
			outlined: "Material+Symbols+Outlined",
			rounded: "Material+Symbols+Rounded",
			sharp: "Material+Symbols+Sharp",
			// "filled" uses the Outlined font with FILL variation setting
			filled: "Material+Symbols+Outlined",
		};

		// Determine which font families are actually needed
		const neededFamilies = new Set<string>();
		for (const style of needed) {
			const family = FONT_FAMILIES[style];
			if (family) neededFamilies.add(family);
		}

		// Remove font links that are no longer needed
		const existingLinks = Array.from(
			document.querySelectorAll<HTMLLinkElement>(
				`link[id^="${MATERIAL_FONT_LINK_ID}"]`,
			),
		);
		for (const link of existingLinks) {
			const family = link.getAttribute("data-family");
			if (!family || !neededFamilies.has(family)) {
				link.remove();
			} else {
				neededFamilies.delete(family); // already loaded
			}
		}

		// Add missing font links
		for (const family of neededFamilies) {
			// eslint-disable-next-line obsidianmd/no-forbidden-elements -- dynamic font loading requires a link element
			const link = document.createElement("link");
			link.id = `${MATERIAL_FONT_LINK_ID}-${family}`;
			link.setAttribute("data-family", family);
			link.rel = "stylesheet";
			link.href = `https://fonts.googleapis.com/css2?family=${family}:opsz,wght,FILL,GRAD@24,100..700,0..1,0`;
			document.head.appendChild(link);
		}
	}

	/**
	 * Walk all rendered callout elements in the document and re-inject their
	 * Lucide SVG icons. Obsidian reads --callout-icon only once at render time,
	 * so the CSS variable change alone does not update the already-rendered SVG.
	 * Material and emoji icons are handled purely by CSS and do not need this.
	 */
	private refreshCalloutIconsInDOM(): void {
		const calloutEls = Array.from(
			document.querySelectorAll<HTMLElement>(".callout[data-callout]"),
		);
		for (const calloutEl of calloutEls) {
			const id = calloutEl.getAttribute("data-callout");
			if (!id) continue;
			const def = this.registry.get(id);
			if (!def || def.icon.type !== "lucide") continue;
			const iconEl = calloutEl.querySelector<HTMLElement>(
				".callout-title .callout-icon",
			);
			if (!iconEl) continue;
			setIcon(iconEl, def.icon.value);
		}
	}

	scheduleInject(): void {
		if (this.debounceTimer !== null) {
			window.clearTimeout(this.debounceTimer);
		}
		this.debounceTimer = window.setTimeout(() => {
			this.inject();
			this.debounceTimer = null;
		}, DEBOUNCE_MS);
	}

	private generateGlobalStyleCSS(): string {
		const gs = this.registry.settings.globalStyle;
		const parts: string[] = ["/* Global callout style */"];

		const props: string[] = [];

		if (gs.borderRadius !== 4) {
			props.push(`  border-radius: ${gs.borderRadius}px;`);
		}

		// Border sides
		const { top, right, bottom, left } = gs.borderSides;
		const allSides = top && right && bottom && left;
		const anySide = top || right || bottom || left;
		const bStyle = `${gs.borderWidth}px solid rgba(var(--callout-color), 0.45)`;

		if (allSides) {
			props.push(`  border: ${bStyle};`);
		} else if (anySide) {
			// Reset any default border first
			props.push(`  border: none;`);
			if (top) props.push(`  border-top: ${bStyle};`);
			if (right) props.push(`  border-right: ${bStyle};`);
			if (bottom) props.push(`  border-bottom: ${bStyle};`);
			if (left) props.push(`  border-left: ${bStyle};`);
		}

		if (props.length > 0) {
			parts.push(`.callout {\n${props.join("\n")}\n}`);
		}

		// Title scale
		if (gs.titleScale !== 1) {
			parts.push(
				`.callout > .callout-title > .callout-title-inner {\n` +
					`  font-size: ${gs.titleScale}em;\n` +
					`}`,
			);
		}

		// Content scale
		if (gs.contentScale !== 1) {
			parts.push(
				`.callout > .callout-content {\n` +
					`  font-size: ${gs.contentScale}em;\n` +
					`}`,
			);
		}

		return parts.join("\n\n");
	}

	/**
	 * Generates a CSS rule that applies the fallback callout's styles to any
	 * callout whose data-callout ID is not explicitly defined.
	 * Uses `:not()` selectors to exclude all known IDs/aliases.
	 */
	private generateFallbackCSS(callouts: CalloutDefinition[]): string {
		const fallbackId = this.registry.settings.fallbackCalloutId;
		if (!fallbackId) return "";

		const fallbackDef = callouts.find((c) => c.id === fallbackId);
		if (!fallbackDef) return "";

		// Collect all known callout IDs and aliases
		const knownIds: string[] = [];
		for (const def of callouts) {
			knownIds.push(def.id);
			if (def.aliases) knownIds.push(...def.aliases);
		}
		// Always exclude the settings-tab preview marker so the gray preview
		// is never tinted by the fallback callout.
		knownIds.push("cs-preview");

		const notSelectors = knownIds
			.map((id) => `:not([data-callout="${id}"])`)
			.join("");

		const lightRgb = hexToRgbString(fallbackDef.colorLight);
		const darkRgb = hexToRgbString(fallbackDef.colorDark);
		const iconCSS = this.getIconCSS(fallbackDef);

		const parts: string[] = [
			"/* Fallback callout style for unrecognized types */",
		];

		// Use `body` prefix + `!important` so the fallback wins over Obsidian's
		// built-in callout color/icon definitions.
		const lightProps: string[] = [
			`  --callout-color: ${lightRgb} !important;`,
		];
		if (iconCSS)
			lightProps.push(`  --callout-icon: ${iconCSS} !important;`);
		if (fallbackDef.bgColorLight) {
			lightProps.push(
				`  background-color: ${fallbackDef.bgColorLight} !important;`,
			);
		}
		parts.push(
			`body .callout${notSelectors} {\n${lightProps.join("\n")}\n}`,
		);

		if (
			fallbackDef.colorLight !== fallbackDef.colorDark ||
			fallbackDef.bgColorLight !== fallbackDef.bgColorDark
		) {
			const darkProps: string[] = [
				`  --callout-color: ${darkRgb} !important;`,
			];
			if (fallbackDef.bgColorDark) {
				darkProps.push(
					`  background-color: ${fallbackDef.bgColorDark} !important;`,
				);
			}
			parts.push(
				`body.theme-dark .callout${notSelectors} {\n${darkProps.join("\n")}\n}`,
			);
		}

		if (fallbackDef.textColorLight) {
			parts.push(
				`body .callout${notSelectors} > .callout-content {\n  color: ${fallbackDef.textColorLight} !important;\n}`,
			);
		}
		if (
			fallbackDef.textColorDark &&
			fallbackDef.textColorDark !== fallbackDef.textColorLight
		) {
			parts.push(
				`body.theme-dark .callout${notSelectors} > .callout-content {\n  color: ${fallbackDef.textColorDark} !important;\n}`,
			);
		}

		// Material SVG icon override for fallback
		if (fallbackDef.icon.type === "material") {
			const cached = this.registry.findMaterialSvg(
				fallbackDef.icon.value,
				fallbackDef.icon.style ?? "outlined",
				fallbackDef.icon.weight ?? 400,
			);
			if (cached) {
				const dataUri = svgToDataUri(cached.svg);
				parts.push(
					`body .callout${notSelectors} > .callout-title > .callout-icon > svg {\n  display: none !important;\n}\n` +
						`body .callout${notSelectors} > .callout-title > .callout-icon::after {\n` +
						`  content: "";\n` +
						`  display: inline-block;\n` +
						`  width: var(--icon-size, 1.2em);\n` +
						`  height: var(--icon-size, 1.2em);\n` +
						`  -webkit-mask-image: ${dataUri} !important;\n` +
						`  mask-image: ${dataUri} !important;\n` +
						`  -webkit-mask-size: contain;\n` +
						`  mask-size: contain;\n` +
						`  -webkit-mask-repeat: no-repeat;\n` +
						`  mask-repeat: no-repeat;\n` +
						`  background-color: rgb(var(--callout-color)) !important;\n` +
						`}`,
				);
			}
		}

		return parts.join("\n\n");
	}

	destroy(): void {
		if (this.debounceTimer !== null) {
			window.clearTimeout(this.debounceTimer);
			this.debounceTimer = null;
		}
		if (this.styleEl) {
			this.styleEl.remove();
			this.styleEl = null;
		}
		// Remove Material font links
		document
			.querySelectorAll(`link[id^="${MATERIAL_FONT_LINK_ID}"]`)
			.forEach((el) => el.remove());
	}
}
