import type { App } from "obsidian";
import type { CalloutDefinition } from "../types";
import { hexToRgbString } from "../utils/colorUtils";
import type { CalloutRegistry } from "./CalloutRegistry";

const STYLE_ELEMENT_ID = "callout-studio-styles";
const DEBOUNCE_MS = 300;

export class CSSInjector {
	private styleEl: HTMLStyleElement | null = null;
	private debounceTimer: number | null = null;
	private registry: CalloutRegistry;
	private app: App;

	constructor(app: App, registry: CalloutRegistry) {
		this.app = app;
		this.registry = registry;
	}

	initialize(): void {
		this.ensureStyleElement();
		this.inject();
	}

	private ensureStyleElement(): void {
		if (this.styleEl) return;
		const existing = document.getElementById(STYLE_ELEMENT_ID) as HTMLStyleElement | null;
		if (existing) {
			this.styleEl = existing;
			return;
		}
		this.styleEl = document.createElement("style");
		this.styleEl.id = STYLE_ELEMENT_ID;
		document.head.appendChild(this.styleEl);
	}

	inject(): void {
		this.ensureStyleElement();
		if (!this.styleEl) return;

		const callouts = this.registry.getAll();
		const rules: string[] = [
			"/* Auto-generated by Callout Studio — do not edit manually */",
		];

		for (const def of callouts) {
			if (def.builtIn) {
				// Only inject CSS for built-in callouts that have been modified
				const defaultDef = this.registry.get(def.id);
				if (!defaultDef) continue;
				// We inject for all non-default built-ins and all user callouts
				// For built-ins, check if colors/icon were changed — the registry
				// handles this via the isModified check on save, but we inject for
				// all here since the registry has already merged overrides
			}

			rules.push(this.generateCalloutCSS(def));
		}

		this.styleEl.textContent = rules.join("\n\n");
	}

	private generateCalloutCSS(def: CalloutDefinition): string {
		const lightRgb = hexToRgbString(def.colorLight);
		const darkRgb = hexToRgbString(def.colorDark);
		const iconCSS = this.getIconCSS(def);

		const parts: string[] = [];

		// Light mode (default)
		parts.push(
			`.callout[data-callout="${def.id}"] {\n` +
			`  --callout-color: ${lightRgb};\n` +
			(iconCSS ? `  --callout-icon: ${iconCSS};\n` : "") +
			`}`
		);

		// Dark mode override (only if different from light)
		if (def.colorLight !== def.colorDark) {
			parts.push(
				`.theme-dark .callout[data-callout="${def.id}"] {\n` +
				`  --callout-color: ${darkRgb};\n` +
				`}`
			);
		}

		return parts.join("\n\n");
	}

	private getIconCSS(def: CalloutDefinition): string {
		switch (def.icon.type) {
			case "lucide":
				return `lucide-${def.icon.value}`;
			case "svg": {
				const encoded = encodeURIComponent(def.icon.value);
				return `"data:image/svg+xml,${encoded}"`;
			}
			case "material":
				// Material icons are handled via font, not CSS variable
				// We'll set a placeholder and handle rendering separately
				return `lucide-pencil`;
			case "emoji":
				return `"${def.icon.value}"`;
			default:
				return "";
		}
	}

	scheduleInject(): void {
		if (this.debounceTimer !== null) {
			window.clearTimeout(this.debounceTimer);
		}
		this.debounceTimer = window.setTimeout(() => {
			this.inject();
			this.debounceTimer = null;
		}, DEBOUNCE_MS);
	}

	destroy(): void {
		if (this.debounceTimer !== null) {
			window.clearTimeout(this.debounceTimer);
			this.debounceTimer = null;
		}
		if (this.styleEl) {
			this.styleEl.remove();
			this.styleEl = null;
		}
	}
}
