/**
 * manager/cssSnippetFile.ts — what a Callout Studio CSS snippet looks like on
 * disk: its preamble, the fingerprint in it, and the one question that
 * fingerprint exists to answer.
 *
 * Split out of {@link exportCssSnippet} because it is a different job. That
 * module decides *what CSS* to write and *whether* to write it; this one owns
 * the file format, which is the half that has to stay stable — the preamble is
 * read by a person opening the file, and the fingerprint is read back by the
 * next export.
 */

/** First bytes of a file this plugin wrote. */
const MARKER = "/* Generated by Callout Studio";

/** Closes the header comment. The body is everything after it. */
const HEADER_END = " */\n\n";

/** The fingerprint line, read back out of a file's own header. */
const FINGERPRINT_RE = /\n \* fingerprint: ([0-9a-f]{64})$/;

async function sha256(text: string): Promise<string> {
	// Third copy of this in the plugin (PackDataStore.verify, LocaleStore) —
	// left local rather than extracted, so this change stays inside its feature.
	const bytes = new TextEncoder().encode(text);
	const digest = await crypto.subtle.digest("SHA-256", bytes);
	return Array.from(new Uint8Array(digest))
		.map((b) => b.toString(16).padStart(2, "0"))
		.join("");
}

/**
 * The finished file: a header carrying a fingerprint of everything below it,
 * then the body.
 *
 * The fingerprint is the line that lets a later export tell "the settings
 * changed" apart from "the user edited this file", which are otherwise the same
 * diff. Deliberately no timestamp and no version: identical settings must
 * produce identical bytes, or every export would rewrite the file and sync it.
 *
 * The prose is the short form of the README's *Export as a CSS snippet*, and
 * says the three things someone who finds this file without that page still
 * needs: it does not update itself, nothing here switched it on, and it covers
 * the block form of a callout only.
 */
export async function buildSnippetFile(body: string): Promise<string> {
	const fingerprint = await sha256(body);
	return (
		"/* Generated by Callout Studio — do not edit.\n" +
		" *\n" +
		" * A SNAPSHOT, taken when you exported. It does not update itself: after\n" +
		" * changing a callout, export again from Settings → Callout Studio →\n" +
		" * Import / export, which replaces this file.\n" +
		" *\n" +
		" * Callout Studio never switches this snippet on. Obsidian, though,\n" +
		" * remembers enabled snippets by NAME and keeps the name after the file is\n" +
		" * gone — so if you enabled an earlier copy, this one is live the moment it\n" +
		" * appears. Check under Settings → Appearance → CSS snippets.\n" +
		" *\n" +
		" * Covers regular callouts (> [!type]) only: colours, backgrounds (flat,\n" +
		" * gradient or transparent), icons, borders, sizes and aliases, in both\n" +
		" * modes. Heading and inline callouts are Callout Studio's own elements and\n" +
		" * cannot be reproduced in plain CSS, so they are absent, as is the\n" +
		" * fallback style. In PDF export a non-Lucide icon prints as a pencil:\n" +
		" * printing one needs a real SVG element in the page, and a stylesheet can\n" +
		" * style an element but never create one. Colours and gradients do print.\n" +
		" *\n" +
		" * Written for the theme that was active when you exported: how a theme\n" +
		" * spells its callout colours decides what this file has to say, so under a\n" +
		" * very different theme some of it may be redundant or, in the accent, off.\n" +
		` * fingerprint: ${fingerprint}${HEADER_END}` +
		body
	);
}

/** What is at the target path right now. */
export type Existing =
	| { kind: "missing" }
	| { kind: "ours"; text: string }
	| { kind: "foreign" };

/**
 * "Ours" means we wrote it and nobody has touched it since. Anything else — a
 * foreign file, a hand-edited one, one we cannot read — is `foreign`: the
 * answer that costs a confirmation rather than the user their edit.
 */
export async function classifyExisting(text: string): Promise<Existing> {
	if (!text.startsWith(MARKER)) return { kind: "foreign" };
	const split = text.indexOf(HEADER_END);
	if (split < 0) return { kind: "foreign" };
	// `split` lands on the space before `*/`, so this slice ends exactly at the
	// last hex digit — which is what the `$` in FINGERPRINT_RE anchors to.
	const stamp = FINGERPRINT_RE.exec(text.slice(0, split));
	if (!stamp) return { kind: "foreign" };
	const body = text.slice(split + HEADER_END.length);
	return (await sha256(body)) === stamp[1]
		? { kind: "ours", text }
		: { kind: "foreign" };
}
