/**
 * manager/StartupStyleCache.ts — kills the "flash of unstyled callouts" at
 * app startup, most visible on mobile where Obsidian renders the restored
 * note BEFORE community plugins finish loading.
 *
 * Two snapshot layers, both refreshed from CSSInjector.inject() and both
 * always on (deliberately no settings toggle — see README, "Network usage
 * and privacy"):
 *
 * 1. CSS snippet (`.obsidian/snippets/callout-studio-do-not-delete.css`) —
 *    Obsidian loads enabled snippets during app CSS init, before any
 *    community plugin runs, so callout colors/backgrounds/icons are correct
 *    from the very first frame. This fully eliminates the color flash. The
 *    snippet is self-healing: every launch recreates the file if it was
 *    deleted and re-enables it if it was toggled off (see
 *    ensureSnippetEnabled), so an accidental disable or vault cleanup never
 *    silently reintroduces the startup flash.
 * 2. localStorage (per device, vault-scoped) — read synchronously by
 *    CSSInjector.injectFromCache() as the very first statement of plugin
 *    onload, before `loadData()` is awaited. This shrinks the plugin-side
 *    delay for everything a snippet cannot cover (e.g. while snippets are
 *    disabled, or before the snippet file exists on a fresh install).
 *
 * Both layers hold the exact same text the adopted stylesheet gets, so the
 * handoff to the live-generated CSS is invisible. A stale snapshot (edit made
 * less than the debounce before quitting) self-heals: the next launch's
 * inject() persists the fresh CSS again.
 */
import { normalizePath } from "obsidian";
import type { App } from "obsidian";

const LOCAL_STORAGE_KEY = "callout-studio-css";
/** The "do-not-delete" in the name warns users (and vault-cleanup habits)
 * away from stripping the file and silently reintroducing the startup
 * flash. Deleting it is still harmless — it comes back on the next launch. */
const SNIPPET_NAME = "callout-studio-do-not-delete";
/** Snippet writes hit disk (and vault sync) — debounce them well beyond the
 * 300ms inject debounce so a burst of edits lands as one write. */
const SNIPPET_WRITE_DEBOUNCE_MS = 2000;

const SNIPPET_HEADER =
	"/* Auto-generated by the Callout Studio plugin — do not edit.\n" +
	" * Purpose: applies your callout styling during app startup, before\n" +
	" * community plugins load (removes the brief unstyled flash on mobile).\n" +
	" * Deleting or disabling it only brings that flash back until the next\n" +
	" * launch, when the plugin recreates and re-enables it automatically. */\n\n";

/**
 * The undocumented subset of Obsidian's `app.customCss` this module relies
 * on. Both methods are probed for existence before use; if the internal API
 * ever changes, the snippet file still works — the user just has to enable
 * it manually (or it simply stays a no-op file).
 */
interface CustomCssApi {
	setCssEnabledStatus?: (snippetName: string, enabled: boolean) => void;
	requestLoadSnippets?: () => void;
	enabledSnippets?: Set<string>;
}

export class StartupStyleCache {
	private app: App;
	/** Last CSS handed to persist() — dedupes the no-op injects that follow
	 * every external css-change event. */
	private lastPersisted: string | null = null;
	private pendingCss: string | null = null;
	private snippetTimer: number | null = null;

	constructor(app: App) {
		this.app = app;
	}

	/**
	 * Vault-scoped localStorage key. Mirrors the `${appId}-${key}` convention
	 * of `App.loadLocalStorage`, which we can't call directly: it requires
	 * Obsidian 1.8.7 while our minAppVersion is 1.6.6. `appId` is undocumented
	 * but long-stable; the vault name is the fallback scope.
	 */
	private scopedKey(key: string): string {
		const appId = (this.app as App & { appId?: string }).appId;
		return `${appId ?? this.app.vault.getName()}-${key}`;
	}

	/** Synchronous read of the previous session's CSS (localStorage layer). */
	loadCachedCss(): string | null {
		try {
			const cached = window.localStorage.getItem(
				this.scopedKey(LOCAL_STORAGE_KEY),
			);
			return cached && cached.length > 0 ? cached : null;
		} catch {
			return null;
		}
	}

	/**
	 * Record freshly generated CSS in both snapshot layers. localStorage is
	 * written immediately (cheap, synchronous); the snippet file write is
	 * debounced and content-compared so repeated injects never churn disk or
	 * vault sync.
	 */
	persist(cssText: string): void {
		if (cssText === this.lastPersisted) return;
		this.lastPersisted = cssText;
		try {
			window.localStorage.setItem(
				this.scopedKey(LOCAL_STORAGE_KEY),
				cssText,
			);
		} catch {
			// Quota exceeded / storage unavailable — the snippet layer and the
			// normal inject path still work, so styling is never lost.
		}

		this.pendingCss = cssText;
		if (this.snippetTimer !== null) window.clearTimeout(this.snippetTimer);
		this.snippetTimer = window.setTimeout(() => {
			this.snippetTimer = null;
			void this.writeSnippet();
		}, SNIPPET_WRITE_DEBOUNCE_MS);
	}

	destroy(): void {
		// Drop any pending write instead of flushing: spawning async disk IO
		// during unload races app quit / plugin uninstall. A lost write is
		// harmless — next launch re-persists (see module header).
		if (this.snippetTimer !== null) {
			window.clearTimeout(this.snippetTimer);
			this.snippetTimer = null;
		}
		this.pendingCss = null;
	}

	private async writeSnippet(): Promise<void> {
		const css = this.pendingCss;
		if (css == null) return;
		this.pendingCss = null;

		try {
			const adapter = this.app.vault.adapter;
			const dir = normalizePath(`${this.app.vault.configDir}/snippets`);
			const path = normalizePath(`${dir}/${SNIPPET_NAME}.css`);
			const content = SNIPPET_HEADER + css;

			if (await adapter.exists(path)) {
				// Skip identical rewrites — every write is a vault-sync event.
				const current = await adapter.read(path);
				if (current !== content) await adapter.write(path, content);
			} else {
				if (!(await adapter.exists(dir))) await adapter.mkdir(dir);
				await adapter.write(path, content);
			}
			this.ensureSnippetEnabled();
		} catch (e) {
			console.warn(
				"[CalloutStudio] failed to write startup CSS snippet",
				e,
			);
		}
	}

	/**
	 * Make sure the snippet is toggled on. Runs after every snippet write —
	 * i.e. on every launch and after every style change — so an accidental
	 * disable under Settings → Appearance is undone the next time the plugin
	 * loads. It also covers sync: another device may create the file and sync
	 * it over while `enabledCssSnippets` (appearance.json) doesn't follow.
	 * When the enabled-snippets set is readable we skip the no-op case, so a
	 * normal launch never touches appearance.json or reloads snippets.
	 */
	private ensureSnippetEnabled(): void {
		const customCss = (this.app as App & { customCss?: CustomCssApi })
			.customCss;
		if (customCss?.enabledSnippets?.has?.(SNIPPET_NAME)) return;
		this.enableSnippet();
	}

	private enableSnippet(): boolean {
		const customCss = (this.app as App & { customCss?: CustomCssApi })
			.customCss;
		if (typeof customCss?.setCssEnabledStatus !== "function") {
			console.warn(
				"[CalloutStudio] app.customCss API unavailable — enable the " +
					`"${SNIPPET_NAME}" snippet manually under Settings → Appearance`,
			);
			return false;
		}
		customCss.setCssEnabledStatus(SNIPPET_NAME, true);
		customCss.requestLoadSnippets?.();
		return true;
	}
}
