/**
 * tests/support/sourceScan.ts — reading this repository as *text*, for the
 * handful of invariants that are about the source rather than about behaviour.
 *
 * The "repo*" suites (`repoRelease`, `repoSourceRules`, `repoStyles`,
 * `repoGenerated`) all assert things no unit test can reach: that no UI string
 * skipped `t()`, that nothing new fetches from the network, that `styles.css`
 * and the code still agree about class names. Every one of those is a question
 * about the bytes on disk, so they all need the same two primitives and both
 * are easy to get subtly wrong:
 *
 * - **{@link blankLiterals}** — the same file with every comment body and every
 *   string/template/regex body replaced by spaces, and *exactly* as long as the
 *   original so a match index still maps to a real line. Without it, "no `any`
 *   in `src/`" fails on the word "anything" in a doc comment, and "no raw
 *   `setInterval`" fails on the sentence describing why there is none. The five
 *   `any`-looking hits in `src/` today are all prose, which is precisely why a
 *   grep-shaped version of these tests would have been worthless.
 * - **{@link literals}** — the opposite view: every string literal's body with
 *   its offset, for the checks that are *about* the strings (class names, CSS
 *   custom properties, hardcoded UI copy).
 *
 * Both come out of one scanner, because a half-scanner is what produces the
 * false positives. It handles TypeScript's four literal forms plus regex
 * literals, including `${…}` holes that nest back into code (and can hold more
 * templates), and it is asserted end-to-end by `tests/repoSourceRules.test.ts`,
 * which fails if the scanner ever finishes a file in a non-code state — an
 * unterminated string means the scan silently swallowed real code, and a check
 * that silently sees nothing passes for the wrong reason.
 *
 * Nothing here parses TypeScript. It cannot tell a type annotation from an
 * expression, so every caller keeps its own narrow regex and uses this only to
 * decide *which bytes are code*. That division is deliberate: a real parser
 * would be a dependency, and the questions being asked are lexical anyway.
 */
import assert from "node:assert";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";

/**
 * The repository root.
 *
 * `npm test` bundles the suites into `.test-out/` and spawns Node from wherever
 * npm ran, which is the project root — the same assumption `locales.test.ts`
 * already makes. It is asserted rather than assumed: a wrong cwd would make
 * every file walk below return an empty list, and an empty list makes each of
 * these suites pass while checking nothing at all.
 */
export const REPO_ROOT = process.cwd();

assert.ok(
	existsSync(join(REPO_ROOT, "manifest.json")) &&
		existsSync(join(REPO_ROOT, "src")),
	`sourceScan: cwd is not the repository root (${REPO_ROOT}). ` +
		"Run the suites through `npm test`.",
);

/** Reads a repo-relative path as UTF-8. */
export function readRepoFile(relPath: string): string {
	return readFileSync(join(REPO_ROOT, relPath), "utf8");
}

/** Reads and parses a repo-relative JSON file. */
export function readRepoJson<T>(relPath: string): T {
	return JSON.parse(readRepoFile(relPath)) as T;
}

/** True when a repo-relative path exists. */
export function repoFileExists(relPath: string): boolean {
	return existsSync(join(REPO_ROOT, relPath));
}

export interface SourceFile {
	/** Repo-relative, always with forward slashes so the checks read the same on Windows. */
	path: string;
	text: string;
	/** {@link blankLiterals} of `text`, computed once and shared by every caller. */
	code: string;
}

/**
 * Sub-trees of `src/` that are data or generated output rather than hand-written
 * plugin code, and that every source rule below therefore excludes.
 *
 * Each is excluded for a reason a reader would otherwise have to guess at:
 *
 * - `src/i18n/` — 32 locale tables. They *are* UI strings, so the "no hardcoded
 *   string" rule would flag all of them; they are ~900 lines each, so the file
 *   size rule would flag all of them; and `ar.ts` happens to contain the
 *   substring `callout-studio-export` inside a translated sentence, which the
 *   class-name scan would otherwise read as a class. `localeManifest.ts` is
 *   generated on top of that.
 * - `src/icons/data/` — packed search indexes, regenerated by
 *   `npm run icons:generate`. Icon *names* in them (`cs-3`, `cs-hub`, `cs-off`,
 *   `cs-yolo`) collide head-on with this plugin's own `cs-` class prefix.
 * - `src/data/` — the emoji and (formerly) Material metadata tables.
 */
const GENERATED_OR_DATA = [
	"src/i18n/",
	"src/icons/data/",
	"src/data/",
] as const;

/** True when `path` is one of the data/generated trees above. */
export function isGeneratedOrData(path: string): boolean {
	return GENERATED_OR_DATA.some((prefix) => path.startsWith(prefix));
}

let cached: SourceFile[] | null = null;
let cachedTests: SourceFile[] | null = null;

/** Every `.ts` file under one repo-relative tree, scanned and blanked. */
function scanTree(relDir: string): SourceFile[] {
	const out: SourceFile[] = [];
	const walk = (dir: string): void => {
		for (const entry of readdirSync(dir).sort()) {
			const full = join(dir, entry);
			if (statSync(full).isDirectory()) {
				walk(full);
				continue;
			}
			if (!full.endsWith(".ts")) continue;
			const text = readFileSync(full, "utf8");
			out.push({
				path: relative(REPO_ROOT, full).split(sep).join("/"),
				text,
				code: blankLiterals(text),
			});
		}
	};
	walk(join(REPO_ROOT, relDir));
	return out;
}

/**
 * Every `.ts` file under `src/`, scanned once and memoised.
 *
 * The scan is the expensive part (176 files, ~71k lines), and five suites want
 * it, so it happens once per `npm test` process rather than once per assertion.
 */
export function allSourceFiles(): SourceFile[] {
	cached ??= scanTree("src");
	return cached;
}

/**
 * Every `.ts` file under `tests/`, the suites and their support modules alike.
 *
 * They are source too: `tsconfig.json` includes them, so `npm run build`
 * typechecks them, and the rules that follow from that (see
 * `tests/repoTestGate.test.ts`) need to read them the same way.
 */
export function testSourceFiles(): SourceFile[] {
	cachedTests ??= scanTree("tests");
	return cachedTests;
}

/** Hand-written plugin source: {@link allSourceFiles} minus the data trees. */
export function pluginSourceFiles(): SourceFile[] {
	return allSourceFiles().filter((f) => !isGeneratedOrData(f.path));
}

/* -------------------------------------------------------------------------- */
/* The scanner                                                                */
/* -------------------------------------------------------------------------- */

export type LiteralKind = "string" | "template" | "regex";

export interface Literal {
	kind: LiteralKind;
	/** The body, between the delimiters, exactly as written (escapes intact). */
	value: string;
	/** Offset of the opening delimiter in the original text. */
	start: number;
	/** Offset just past the closing delimiter. */
	end: number;
}

interface ScanResult {
	blanked: string;
	literals: Literal[];
	/** True when the file ended in code — see the note in the file header. */
	balanced: boolean;
}

/**
 * Characters and keywords after which a `/` opens a regex rather than dividing.
 *
 * This is the one genuinely ambiguous thing in the grammar, and getting it
 * wrong is not cosmetic: reading `/["']/` as division leaves an *unterminated
 * string* open, and the rest of the file is then blanked away as string body.
 * The `balanced` flag exists to turn that into a loud failure instead of a
 * quietly-passing check.
 */
const REGEX_PRECEDERS = new Set("(,=:[!&|?{};+-*%~^<>");
const REGEX_KEYWORDS = new Set([
	"return",
	"typeof",
	"instanceof",
	"in",
	"of",
	"new",
	"delete",
	"void",
	"case",
	"do",
	"else",
	"yield",
	"await",
]);

/**
 * One entry of the scanner's mode stack.
 *
 * The bottom entry is always a `code` frame that no `}` can pop (`fromHole`
 * false). A backtick pushes a `template` frame; a `${` inside that template
 * pushes a `code` frame with `fromHole` true, and the `}` that balances it pops
 * back to the template. `braces` counts the `{` opened *inside* a hole so an
 * object literal in an interpolation does not close it early.
 */
interface Frame {
	kind: "code" | "template";
	fromHole: boolean;
	braces: number;
}

function scan(text: string): ScanResult {
	// Same length as `text` throughout: every branch writes exactly as many
	// characters as it consumed, so an index into `blanked` is an index into
	// `text`.
	const out: string[] = new Array<string>(text.length).fill(" ");
	const found: Literal[] = [];
	const stack: Frame[] = [{ kind: "code", fromHole: false, braces: 0 }];
	let i = 0;
	// The last non-whitespace code character, and the identifier ending at it —
	// together they are what decides `/` between regex and division.
	let lastSignificant = "";
	let lastWord = "";

	/** Copies `text[from..to)` through verbatim except newlines-as-newlines. */
	const blank = (from: number, to: number): void => {
		for (let k = from; k < to && k < text.length; k++) {
			out[k] = text[k] === "\n" ? "\n" : " ";
		}
	};
	const keep = (k: number): void => {
		out[k] = text[k] as string;
	};
	const advance = (c: string): void => {
		if (/\s/.test(c)) return;
		lastSignificant = c;
		lastWord = /[A-Za-z_$0-9]/.test(c) ? lastWord + c : "";
	};

	while (i < text.length) {
		const frame = stack[stack.length - 1] as Frame;

		// ── inside a template's text ────────────────────────────────────
		if (frame.kind === "template") {
			const start = i;
			let j = i;
			while (j < text.length) {
				if (text[j] === "\\") {
					j += 2;
					continue;
				}
				if (text[j] === "`") break;
				if (text[j] === "$" && text[j + 1] === "{") break;
				j++;
			}
			blank(start, j);
			if (j > start) {
				found.push({
					kind: "template",
					value: text.slice(start, j),
					start,
					end: j,
				});
			}
			i = j;
			if (text[i] === "`") {
				keep(i);
				i++;
				stack.pop();
				advance("`");
			} else if (text[i] === "$") {
				// Enter the interpolation: the `${` is kept so a caller can see
				// that the literal had a hole here.
				keep(i);
				keep(i + 1);
				i += 2;
				stack.push({ kind: "code", fromHole: true, braces: 0 });
				advance("{");
			}
			// Otherwise the file ended mid-template; the loop exits and
			// `balanced` reports it.
			continue;
		}

		const c = text[i] as string;
		const next = text[i + 1];

		// ── comments ────────────────────────────────────────────────────
		if (c === "/" && next === "/") {
			let j = i;
			while (j < text.length && text[j] !== "\n") j++;
			blank(i, j);
			i = j;
			continue;
		}
		if (c === "/" && next === "*") {
			let j = i + 2;
			while (j < text.length && !(text[j] === "*" && text[j + 1] === "/")) j++;
			j = Math.min(j + 2, text.length);
			blank(i, j);
			i = j;
			continue;
		}

		// ── quoted strings ──────────────────────────────────────────────
		if (c === '"' || c === "'") {
			const start = i;
			let j = i + 1;
			while (j < text.length && text[j] !== c && text[j] !== "\n") {
				j += text[j] === "\\" ? 2 : 1;
			}
			const closed = text[j] === c;
			const bodyEnd = j;
			const end = closed ? j + 1 : j;
			keep(start);
			blank(start + 1, bodyEnd);
			if (closed) keep(bodyEnd);
			found.push({
				kind: "string",
				value: text.slice(start + 1, bodyEnd),
				start,
				end,
			});
			i = end;
			advance(c);
			continue;
		}

		// ── template start ──────────────────────────────────────────────
		if (c === "`") {
			keep(i);
			i++;
			stack.push({ kind: "template", fromHole: false, braces: 0 });
			continue;
		}

		// ── regex literals ──────────────────────────────────────────────
		if (c === "/" && startsRegex(lastSignificant, lastWord)) {
			let j = i + 1;
			let inClass = false;
			let terminated = false;
			while (j < text.length) {
				const d = text[j] as string;
				if (d === "\\") {
					j += 2;
					continue;
				}
				if (d === "\n") break;
				if (d === "[") inClass = true;
				else if (d === "]") inClass = false;
				else if (d === "/" && !inClass) {
					terminated = true;
					break;
				}
				j++;
			}
			if (terminated) {
				let end = j + 1;
				while (end < text.length && /[a-z]/.test(text[end] as string)) end++;
				keep(i);
				blank(i + 1, end);
				found.push({ kind: "regex", value: text.slice(i + 1, j), start: i, end });
				i = end;
				advance("/");
				continue;
			}
			// Not a regex after all — it was division. Fall through as code.
		}

		// ── plain code ──────────────────────────────────────────────────
		keep(i);
		if (c === "{") frame.braces++;
		else if (c === "}") {
			if (frame.fromHole && frame.braces === 0) {
				stack.pop();
				i++;
				advance("}");
				continue;
			}
			frame.braces--;
		}
		advance(c);
		i++;
	}

	return {
		blanked: out.join(""),
		literals: found,
		balanced: stack.length === 1,
	};
}

function startsRegex(lastSignificant: string, lastWord: string): boolean {
	if (lastSignificant === "") return true;
	if (REGEX_KEYWORDS.has(lastWord)) return true;
	return REGEX_PRECEDERS.has(lastSignificant);
}

/**
 * `text` with every comment, string, template and regex *body* replaced by
 * spaces, and the same length as the original.
 */
export function blankLiterals(text: string): string {
	return scan(text).blanked;
}

/** Nonblank lines containing code or literal text, excluding comment-only lines. */
export function codeLineCount(text: string): number {
	const { blanked, literals: found } = scan(text);
	const uncommented = blanked.split("");
	// Restore literal contents: comment markers inside strings, regexes and
	// template text are data. Template interpolation comments stay blanked.
	for (const { start, end } of found) {
		for (let i = start; i < end; i++) uncommented[i] = text[i] as string;
	}
	return uncommented.join("").split(/\r\n|\n|\r/).filter((line) => line.trim()).length;
}

/** Every string/template/regex literal body in `text`, with its offsets. */
export function literals(text: string): Literal[] {
	return scan(text).literals;
}

/** True when the scanner finished `text` in a code state. */
export function scanIsBalanced(text: string): boolean {
	return scan(text).balanced;
}

/* -------------------------------------------------------------------------- */
/* Small text helpers                                                         */
/* -------------------------------------------------------------------------- */

/** 1-based line number of `index` in `text`. */
export function lineOf(text: string, index: number): number {
	let line = 1;
	for (let i = 0; i < index && i < text.length; i++) {
		if (text[i] === "\n") line++;
	}
	return line;
}

/** `path:line`, the form the IDE turns into a link. */
export function at(file: SourceFile, index: number): string {
	return `${file.path}:${lineOf(file.text, index)}`;
}

/**
 * The span of a call's argument list, given the offset of its opening paren.
 *
 * Counts parens in the *blanked* text so a `(` inside a string does not throw
 * the balance off, and returns offsets into the original so the caller can slice
 * either view. Returns `null` for an unbalanced call, which cannot happen in
 * code that compiles but would otherwise be an infinite hunt.
 */
export function argSpan(
	code: string,
	openParen: number,
): { start: number; end: number } | null {
	let depth = 0;
	for (let i = openParen; i < code.length; i++) {
		const c = code[i];
		if (c === "(") depth++;
		else if (c === ")") {
			depth--;
			if (depth === 0) return { start: openParen + 1, end: i };
		}
	}
	return null;
}

/**
 * Every match of `re` in a file's *code* (literals blanked), as
 * `{ match, index }`. `re` must be global.
 */
export function codeMatches(
	file: SourceFile,
	re: RegExp,
): { match: RegExpMatchArray; index: number }[] {
	const out: { match: RegExpMatchArray; index: number }[] = [];
	for (const m of file.code.matchAll(re)) {
		out.push({ match: m, index: m.index ?? 0 });
	}
	return out;
}

/**
 * Formats a list of offending sites for an assertion message.
 *
 * Every check below reports *all* of its violations rather than the first: the
 * whole value of a ratchet is that you fix the batch once, and a message that
 * names one site at a time turns that into a dozen round trips.
 */
export function report(title: string, lines: string[]): string {
	return `${title}\n  ${lines.join("\n  ")}\n`;
}
