/**
 * utils/calloutCssParse.ts — reading callout definitions back out of CSS.
 *
 * Two quite different things arrive as a block of CSS and mean the same thing:
 * what Callout Manager's Copy button puts on the clipboard, and what this
 * plugin itself generates. The second is why this matters beyond migration — a
 * user whose settings file was lost can recover colours and icons from the
 * stylesheet, either the startup snapshot in `localStorage` (see
 * `manager/StartupStyleCache.ts`) or an exported snippet, by pasting it into the
 * same import box. `tests/calloutManagerImport.test.ts` holds that round trip.
 *
 * Split out of `calloutManagerImport.ts`, which is about turning one plugin's
 * saved data into entries; this is about text.
 */
import { parseCssColorToHex } from "./colorUtils";
import { calloutIdentity, normalizeCalloutId } from "./calloutId";
import { validateIdString } from "./importValidator";
import {
	assertImportTextSize,
	ImportLimitError,
	MAX_IMPORT_COLLECTION,
	MAX_IMPORT_VALUES,
} from "./importLimits";
import type { CalloutIcon } from "../types";
import type { CalloutManagerEntry } from "./calloutManagerImport";

const SELECTOR_ID_RE = /data-callout=["']([^"']+)["']/g;

/** Remove comments in one forward pass, including an unfinished final comment. */
function withoutComments(text: string, spend: () => void): string {
	const chunks: string[] = [];
	let start = 0;
	let quote = "";
	for (let i = 0; i < text.length; i++) {
		const char = text[i];
		if (char === "\\") { i++; continue; }
		if (quote) { if (char === quote) quote = ""; continue; }
		if (char === '"' || char === "'") { quote = char; continue; }
		if (char !== "/" || text[i + 1] !== "*") continue;
		spend();
		chunks.push(text.slice(start, i));
		const end = text.indexOf("*/", i + 2);
		if (end < 0) { start = text.length; break; }
		i = end + 1;
		start = end + 2;
	}
	chunks.push(text.slice(start));
	return chunks.join("");
}

/** CM emits repeated declarations for its settings cascade; the last wins. */
function declarations(body: string, spend: () => void): Pick<CalloutManagerEntry, "icon" | "color"> {
	const result: Pick<CalloutManagerEntry, "icon" | "color"> = {};
	const read = (declaration: string) => {
		spend();
		const match = /^--callout-(icon|color)\s*:\s*([\s\S]*)$/i.exec(declaration.trim());
		if (!match) return;
		// Snapshots generated by Callout Studio mark these properties important.
		const value = match[2]!.replace(/!\s*important\s*$/i, "").trim();
		if (match[1]!.toLowerCase() === "icon") {
			result.icon = parseIconDecl(value) ?? result.icon;
		} else {
			result.color = parseCssColorToHex(value) ?? result.color;
		}
	};
	let start = 0;
	let quote = "";
	let parentheses = 0;
	for (let i = 0; i < body.length; i++) {
		const char = body[i];
		if (char === "\\") { i++; continue; }
		if (quote) { if (char === quote) quote = ""; continue; }
		if (char === '"' || char === "'") { quote = char; continue; }
		if (char === "(") parentheses++;
		else if (char === ")") parentheses = Math.max(0, parentheses - 1);
		else if (char === ";" && parentheses === 0) {
			read(body.slice(start, i));
			start = i + 1;
		}
	}
	if (start < body.length) read(body.slice(start));
	return result;
}
/**
 * Turns an Obsidian icon id into our `CalloutIcon` convention: a bare Lucide
 * name. Obsidian's own `--callout-icon` variable (which both Obsidian core and
 * Callout Manager write) always uses the `lucide-` prefixed form, but every
 * render path in this plugin (`renderIcon.ts`, `constants.ts`) stores and
 * consumes the bare name directly with `setIcon`.
 *
 * Callout Manager picks icons with Obsidian's own suggester, so the value is
 * whatever `getIconIds()` listed — which is three different things (see the
 * header of `icons/lucideId.ts`): prefixed core Lucide, bare ids some other
 * plugin registered with `addIcon()`, and a handful of bare Obsidian-internal
 * ids. Stripping only the prefix leaves all three intact and drawable, and
 * whether the id names anything *here* is the planner's `createLucideNameCheck`
 * to decide — a foreign id passes exactly when the plugin that registered it is
 * installed in this vault, which is exactly when it can be drawn.
 */
export function parseIconDecl(raw: string): CalloutIcon | undefined {
	const trimmed = raw.trim();
	if (!trimmed) return undefined;
	const value = trimmed.startsWith("lucide-")
		? trimmed.slice("lucide-".length)
		: trimmed;
	if (!value) return undefined;
	return { type: "lucide", value };
}

/**
 * Parses the pasted text into one entry per callout, keyed by identity.
 * Blocks are merged by id with last-write-wins **per property** (mirrors CSS
 * cascade: a later block for the same id that only sets one property doesn't
 * erase a property an earlier block already set).
 */
export function parseCalloutManagerExport(text: string): CalloutManagerEntry[] {
	assertImportTextSize(text);
	let remaining = MAX_IMPORT_VALUES;
	const spend = () => {
		if (--remaining < 0) throw new ImportLimitError("import.err.tooComplex");
	};
	const css = withoutComments(text, spend);
	const byId = new Map<string, CalloutManagerEntry>();
	let boundary = 0;
	let selectorStart = 0;
	let open = -1;
	let quote = "";
	// No unanchored block regex: a long string without a closing brace used to
	// retry an ever-shorter suffix at every character, freezing the UI.
	for (let i = 0; i < css.length; i++) {
		const char = css[i];
		if (char === "\\") { i++; continue; }
		if (quote) { if (char === quote) quote = ""; continue; }
		if (char === '"' || char === "'") { quote = char; continue; }
		if (char === "{") {
			spend();
			selectorStart = boundary;
			open = i;
			boundary = i + 1;
			continue;
		}
		if (char !== "}") continue;
		spend();
		boundary = i + 1;
		if (open < 0) continue;
		const selector = css.slice(selectorStart, open);
		const body = css.slice(open + 1, i);
		open = -1;
		let parsed: Pick<CalloutManagerEntry, "icon" | "color"> | undefined;
		for (const match of selector.matchAll(SELECTOR_ID_RE)) {
			spend();
			const id = match[1]!;
			parsed ??= declarations(body, spend);
			// Invalid raw IDs must reach the planner separately. Merging a piped
			// or multiline ID first could smuggle its color onto a valid base ID.
			const valid = validateIdString(normalizeCalloutId(id), () => {}, "id", id);
			const key = valid ? calloutIdentity(id) : id;
			const prev = byId.get(key);
			if (!prev && byId.size >= MAX_IMPORT_COLLECTION) {
				throw new ImportLimitError("import.err.tooComplex");
			}
			byId.set(key, {
				id,
				icon: parsed.icon ?? prev?.icon,
				color: parsed.color ?? prev?.color,
			});
		}
	}

	return [...byId.values()];
}
