/**
 * scripts/generate-locales.mjs — Turns the locale sources into downloadable JSON.
 *
 * Run with `npm run i18n:generate`. Unlike `icons:generate` this *is* wired into
 * `npm run build` (as `prebuild`): it touches no network, reads nothing outside
 * the repo and finishes in well under a second, so there is no reason to let its
 * output drift from `src/i18n/*.ts`.
 *
 * Two artefacts:
 *
 * - `locales/<file>.json` — one locale's strings, downloaded on demand and
 *   cached into the plugin folder at runtime. Committed here and served from
 *   jsDelivr at the plugin's own release tag.
 * - `src/i18n/localeManifest.ts` — the byte count and SHA-256 of each of those
 *   files, compiled into `main.js`. This is what lets the runtime refuse a
 *   mis-served download, and what tells it whether the copy already on disk is
 *   the one this build expects or a leftover from an older version.
 *
 * `en` is deliberately absent from both: it stays bundled as the fallback and
 * the first-paint language, so a device that never reaches the network still
 * has a complete UI.
 *
 * Because the manifest is compiled in and the JSON is served from a git tag, the
 * two must never disagree — a stale manifest means every download fails its
 * checksum. Both CI workflows therefore re-run this script and fail on any
 * `git diff`, which is why regenerating is not something anyone has to remember.
 */
import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const I18N_DIR = join(ROOT, "src", "i18n");
const OUT_DIR = join(ROOT, "locales");

/**
 * The on-disk locale format. Bumping this invalidates every cached file, since
 * the runtime rejects a payload whose `format` it does not recognise.
 */
const LOCALE_FORMAT = 1;

/**
 * Modules in `src/i18n/` that are machinery rather than a locale table. `en` is
 * excluded because it ships inside the bundle.
 */
const NOT_A_LOCALE = new Set(["index", "en", "localeManifest", "LocaleStore"]);

/**
 * Evaluate one locale module and hand back its exported table.
 *
 * The sources are TypeScript, so they cannot simply be imported. esbuild is
 * already a devDependency and already the thing that compiles them for the real
 * build, so using it here means the JSON is generated by the same parser that
 * produces `main.js` rather than by a regex that would drift.
 */
async function readLocaleTable(file) {
	const result = await esbuild.build({
		entryPoints: [join(I18N_DIR, `${file}.ts`)],
		tsconfig: join(ROOT, "scripts/tsconfig.json"),
		bundle: true,
		format: "cjs",
		platform: "neutral",
		write: false,
		logLevel: "silent",
	});
	const code = result.outputFiles[0].text;
	const module = { exports: {} };
	new Function("module", "exports", code)(module, module.exports);

	const table = module.exports[file];
	if (!table || typeof table !== "object") {
		throw new Error(
			`${file}.ts does not export a table named "${file}" — ` +
				`found ${JSON.stringify(Object.keys(module.exports))}`,
		);
	}
	for (const [key, value] of Object.entries(table)) {
		if (typeof value !== "string") {
			throw new Error(
				`${file}.ts: key "${key}" is ${typeof value}, expected a string`,
			);
		}
	}
	return table;
}

function writeLocaleFile(file, strings) {
	mkdirSync(OUT_DIR, { recursive: true });
	// Compact: this file is downloaded over the network and parsed on device.
	const json = JSON.stringify({ format: LOCALE_FORMAT, locale: file, strings });
	writeFileSync(join(OUT_DIR, `${file}.json`), json);
	return {
		bytes: Buffer.byteLength(json, "utf8"),
		sha256: createHash("sha256").update(json, "utf8").digest("hex"),
		keys: Object.keys(strings).length,
	};
}

function writeManifest(entries) {
	const body = entries
		.map(
			([file, e]) =>
				`\t${JSON.stringify(file)}: {\n` +
				`\t\tbytes: ${e.bytes},\n` +
				`\t\tsha256: ${JSON.stringify(e.sha256)},\n` +
				`\t\tkeys: ${e.keys},\n` +
				`\t},`,
		)
		.join("\n");

	const source = `/**
 * i18n/localeManifest.ts — GENERATED FILE, do not edit.
 *
 * What each downloadable locale file should contain, baked into the build by
 * scripts/generate-locales.mjs. Regenerate with \`npm run i18n:generate\`; the
 * build does it for you, and CI fails if the result differs from what is
 * committed.
 *
 * Knowing the exact bytes and SHA-256 up front is what makes the download safe
 * to justify — a mis-served or tampered response cannot be accepted — and it
 * doubles as the staleness signal: a cached file whose hash no longer matches
 * this table is one an older version of the plugin downloaded.
 */

/** The on-disk locale format this build understands. */
export const LOCALE_FORMAT = ${LOCALE_FORMAT};

/** A locale file's id, which is its source module name (\`zhTW\`, not \`zh-tw\`). */
export type LocaleFileId = keyof typeof LOCALE_MANIFEST;

export interface LocaleManifestEntry {
	/** Exact size of the JSON file, as a cheap gate before hashing. */
	bytes: number;
	/** SHA-256 of the file's bytes, verified before anything is registered. */
	sha256: string;
	/** How many strings it holds. Diagnostics only. */
	keys: number;
}

export const LOCALE_MANIFEST = {
${body}
} as const satisfies Record<string, LocaleManifestEntry>;
`;
	writeFileSync(join(I18N_DIR, "localeManifest.ts"), source);
}

async function main() {
	const files = readdirSync(I18N_DIR)
		.filter((f) => f.endsWith(".ts"))
		.map((f) => f.slice(0, -3))
		.filter((f) => !NOT_A_LOCALE.has(f))
		.sort();

	if (files.length === 0) throw new Error("no locale sources found");

	const en = await readLocaleTable("en");
	const enKeys = new Set(Object.keys(en));

	const entries = [];
	for (const file of files) {
		const strings = await readLocaleTable(file);
		const info = writeLocaleFile(file, strings);
		entries.push([file, info]);

		// Reported, never enforced: `en.ts` is edited alone by design, so a locale
		// missing the newest keys is the normal state between a change and its
		// translation pass. `t()` falls back to English per key, so it is a
		// cosmetic gap, not a break. Extra keys are worth knowing about — nothing
		// can reach them once the English key they mirrored is gone.
		const missing = [...enKeys].filter((k) => !(k in strings)).length;
		const extra = Object.keys(strings).filter((k) => !enKeys.has(k));
		const notes = [];
		if (missing > 0) notes.push(`${missing} missing`);
		if (extra.length > 0) notes.push(`${extra.length} not in en: ${extra.join(", ")}`);
		console.log(
			`${file.padEnd(6)} ${String(info.keys).padStart(4)} keys  ` +
				`${(info.bytes / 1024).toFixed(1).padStart(6)} KB` +
				(notes.length > 0 ? `  (${notes.join("; ")})` : ""),
		);
	}

	writeManifest(entries);

	const total = entries.reduce((sum, [, e]) => sum + e.bytes, 0);
	console.log(
		`\n${entries.length} locales → locales/*.json (${(total / 1024).toFixed(0)} KB total), ` +
			`manifest → src/i18n/localeManifest.ts\n` +
			`en stays bundled (${enKeys.size} keys).`,
	);
}

await main();
