import type {
	CalloutDefinition,
	GlobalStyleSettings,
	PluginSettings,
} from "./types";

/** Maximum characters allowed per callout ID */
export const MAX_TAG_LENGTH: number = 10;

/** Maximum number of IDs (aliases) allowed per callout */
export const MAX_TAGS_COUNT: number = 4;

export const DEFAULT_CALLOUTS: CalloutDefinition[] = [
	{
		id: "note",
		displayName: "Note",
		icon: { type: "lucide", value: "pencil" },
		colorLight: "#448aff",
		colorDark: "#448aff",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "abstract",
		displayName: "Abstract",
		icon: { type: "lucide", value: "clipboard-list" },
		colorLight: "#00bcd4",
		colorDark: "#00bcd4",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
		aliases: ["summary", "tldr"],
	},
	{
		id: "info",
		displayName: "Info",
		icon: { type: "lucide", value: "info" },
		colorLight: "#448aff",
		colorDark: "#448aff",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "todo",
		displayName: "Todo",
		icon: { type: "lucide", value: "check-circle-2" },
		colorLight: "#448aff",
		colorDark: "#448aff",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "tip",
		displayName: "Tip",
		icon: { type: "lucide", value: "flame" },
		colorLight: "#00bfa5",
		colorDark: "#00bfa5",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
		aliases: ["hint", "important"],
	},
	{
		id: "success",
		displayName: "Success",
		icon: { type: "lucide", value: "check" },
		colorLight: "#00c853",
		colorDark: "#00c853",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
		aliases: ["check", "done"],
	},
	{
		id: "question",
		displayName: "Question",
		icon: { type: "lucide", value: "help-circle" },
		colorLight: "#ff9100",
		colorDark: "#ff9100",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
		aliases: ["help", "faq"],
	},
	{
		id: "warning",
		displayName: "Warning",
		icon: { type: "lucide", value: "alert-triangle" },
		colorLight: "#ff9100",
		colorDark: "#ff9100",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
		aliases: ["caution", "attention"],
	},
	{
		id: "failure",
		displayName: "Failure",
		icon: { type: "lucide", value: "x" },
		colorLight: "#ff5252",
		colorDark: "#ff5252",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
		aliases: ["fail", "missing"],
	},
	{
		id: "danger",
		displayName: "Danger",
		icon: { type: "lucide", value: "zap" },
		colorLight: "#ff1744",
		colorDark: "#ff1744",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
		aliases: ["error"],
	},
	{
		id: "bug",
		displayName: "Bug",
		icon: { type: "lucide", value: "bug" },
		colorLight: "#ff5252",
		colorDark: "#ff5252",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "example",
		displayName: "Example",
		icon: { type: "lucide", value: "list" },
		colorLight: "#7c4dff",
		colorDark: "#7c4dff",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "quote",
		displayName: "Quote",
		icon: { type: "lucide", value: "quote" },
		colorLight: "#9e9e9e",
		colorDark: "#9e9e9e",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
		aliases: ["cite"],
	},
];

export const DEFAULT_SETTINGS: PluginSettings = {
	globalStyle: {
		borderSides: { top: false, right: false, bottom: false, left: false },
		borderWidth: 1.5,
		alignToTitle: false,
		titleScale: 1,
		contentScale: 1,
		borderRadius: 4,
	} satisfies GlobalStyleSettings,
	popup: {
		enabled: true,
		position: "top-left",
		transparency: 15,
		backdropBlur: 8,
		showIcons: true,
		showColorDots: true,
		maxItems: 8,
		showEditCallout: true,
		showOpenSettings: true,
		showCopyMarkdown: true,
		showEditButton: true,
		animation: "scale",
	},
	autocomplete: {
		enabled: true,
		showIconPreviews: true,
		showColorPreviews: true,
	},
	iconSources: {
		materialStyleDefault: "outlined",
		materialWeightDefault: 400,
	},
	colorMode: {
		mode: "auto",
		format: "hex",
		showContrastWarning: true,
	},
	language: "auto",
};
