import type { CalloutDefinition, PluginSettings } from "./types";

export const DEFAULT_CALLOUTS: CalloutDefinition[] = [
	{
		id: "note",
		displayName: "Note",
		icon: { type: "lucide", value: "pencil" },
		colorLight: "#448aff",
		colorDark: "#448aff",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "abstract",
		displayName: "Abstract",
		icon: { type: "lucide", value: "clipboard-list" },
		colorLight: "#00bcd4",
		colorDark: "#00bcd4",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "info",
		displayName: "Info",
		icon: { type: "lucide", value: "info" },
		colorLight: "#448aff",
		colorDark: "#448aff",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "tip",
		displayName: "Tip",
		icon: { type: "lucide", value: "flame" },
		colorLight: "#00bfa5",
		colorDark: "#00bfa5",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "success",
		displayName: "Success",
		icon: { type: "lucide", value: "check" },
		colorLight: "#00c853",
		colorDark: "#00c853",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "question",
		displayName: "Question",
		icon: { type: "lucide", value: "help-circle" },
		colorLight: "#ff9100",
		colorDark: "#ff9100",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "warning",
		displayName: "Warning",
		icon: { type: "lucide", value: "alert-triangle" },
		colorLight: "#ff9100",
		colorDark: "#ff9100",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "failure",
		displayName: "Failure",
		icon: { type: "lucide", value: "x" },
		colorLight: "#ff5252",
		colorDark: "#ff5252",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "danger",
		displayName: "Danger",
		icon: { type: "lucide", value: "zap" },
		colorLight: "#ff1744",
		colorDark: "#ff1744",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "bug",
		displayName: "Bug",
		icon: { type: "lucide", value: "bug" },
		colorLight: "#ff5252",
		colorDark: "#ff5252",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "example",
		displayName: "Example",
		icon: { type: "lucide", value: "list" },
		colorLight: "#7c4dff",
		colorDark: "#7c4dff",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
	{
		id: "quote",
		displayName: "Quote",
		icon: { type: "lucide", value: "quote" },
		colorLight: "#9e9e9e",
		colorDark: "#9e9e9e",
		foldable: true,
		defaultFolded: false,
		builtIn: true,
		source: "builtin",
	},
];

export const DEFAULT_SETTINGS: PluginSettings = {
	popup: {
		enabled: true,
		position: "top-left",
		transparency: 15,
		backdropBlur: 8,
		showIcons: true,
		showColorDots: true,
		maxItems: 8,
		showConvertSubmenu: true,
		showEditButton: true,
		animation: "scale",
	},
	autocomplete: {
		enabled: true,
		showIconPreviews: true,
		showColorPreviews: true,
		maxSuggestions: 10,
	},
	iconSources: {
		lucide: true,
		material: true,
		customSvg: true,
		materialStyleDefault: "outlined",
		cacheMaterialOffline: true,
	},
	colorMode: {
		mode: "auto",
		format: "hex",
		showContrastWarning: true,
	},
	language: "auto",
};
